config/routes.rb
Rnr::Application.routes.draw do

  root 'vacation_balance_request#index'
  get 'calculate' => 'vacation_balance_request#calculate'

  post '/auth/saml/callback' => 'sessions#okta_store', as: 'okta_login_success'
  get '/auth/salesforcesandbox/callback' => 'sessions#salesforce_store', as: 'salesforce_login_success'
  get '/auth/failure' => 'sessions#failure', as: 'login_failure'
  get '/logout' => 'sessions#destroy', as: 'logout'

end

app/models/session.rb
class Session < ActiveRecord::Base
  def self.sweep(time = 1.hour)
    time = time.split.inject { |count, unit|
      count.to_i.send(unit)
    } if time.is_a?(String)

    delete_all "updated_at < '#{time.ago.to_s(:db)}' OR created_at < '#{2.days.ago.to_s(:db)}'"
  end
end

app/models/vacation_balance_request.rb
require 'active_model'

class VacationBalanceRequest
  include ActiveModel::Model

  attr_accessor :vacation_balance, :start_date, :end_date, :accrual_rate, :salesforce_text

  validates_numericality_of :vacation_balance
  validates_numericality_of :accrual_rate, only_integer: true, greater_than_or_equal_to: 10
  validate :validate_dates
  validates :start_date, format: { with: /\d{4}\/\d{2}\/\d{2}/, message: 'is not in format: yyyy/mm/dd'}
  validates :end_date, format: { with: /\d{4}\/\d{2}\/\d{2}/, message: 'is not in format: yyyy/mm/dd'}

  private
  def validate_dates
    if !start_date.nil? and !end_date.nil?
      errors.add(:end_date, "can't be before the start date") if end_date < start_date
    end
  end
end

app/models/vacation_calculator.rb
require 'active_model'

class VacationCalculator
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :vacation_balance, :start_date, :end_date, :accrual_rate

  validates_numericality_of :vacation_balance
  validates :accrual_rate, numericality: {only_integer: true, greater_than_or_equal_to: 10}
  validates :start_date, presence: true
  validates :end_date, presence: true
  validate :validate_dates

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

  def validate_dates
    errors.add(:end_date, "can't be before the start date") if end_date < start_date
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :require_login if Rails.env.production?

  def require_login
    if session[:userinfo]
      @current_user = session[:current_user]
    else
      redirect_to '/auth/saml'
    end
  end
end

app/controllers/callback_controller.rb
class CallbackController < ApplicationController
  skip_before_action :require_login
  skip_before_filter :verify_authenticity_token, only: [:okta_store, :salesforce_store]

  def okta_store
    session[:userinfo] = request.env['omniauth.auth']
    redirect_to '/auth/salesforcesandbox'
  end

  def salesforce_store
    puts "#{request.env['omniauth.auth']['info']['name']} just authenticated"
    session[:current_user] = request.env['omniauth.auth']['info']['name']
    credentials = request.env["omniauth.auth"]["credentials"]
    session[:token] = credentials["token"]
    session[:refresh_token] = credentials["refresh_token"]
    session[:instance_url] = credentials["instance_url"]
    redirect_to root_path
  end

  def failure
    @error_msg = request.params['message']
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login
  skip_before_filter :verify_authenticity_token, only: [:okta_store, :salesforce_store]

  def okta_store
    reset_session
    session[:userinfo] = request.env['omniauth.auth']
    redirect_to '/auth/salesforcesandbox'
  end

  def salesforce_store
    puts "#{request.env['omniauth.auth']['info']['name']} just authenticated"
    session[:current_user] = request.env['omniauth.auth']['info']['name']
    credentials = request.env["omniauth.auth"]["credentials"]
    session[:token] = credentials["token"]
    session[:refresh_token] = credentials["refresh_token"]
    session[:instance_url] = credentials["instance_url"]
    redirect_to root_path
  end

  def failure
    @error_msg = request.params['message']
    redirect_to '/auth/saml'
  end

  def destroy
    reset_session
    redirect_to 'https://thoughtworks.oktapreview.com/login/signout?fromURI=https://rnr-rails.herokuapp.com'
  end
end

app/controllers/vacation_balance_request_controller.rb
class VacationBalanceRequestController < ApplicationController
  include VacationBalanceRequestHelper

  def index
    @vacation_balance_request = VacationBalanceRequest.new
  end

  def calculate
    @vacation_balance_request = VacationBalanceRequest.new(vacation_balance_request_params)
    @vacation_balance_request.valid?
    first_thing = client.query("SELECT pse__Start_Date__c, pse__Milestone__r.Name, pse__Timecard_Header__r.pse__Total_Hours__c FROM pse__Timecard__c WHERE pse__Milestone__r.Name = 'Annual lv; vacation'").first
    puts first_thing.pse__Milestone__r.Name
    puts first_thing.pse__Start_Date__c
    puts first_thing.pse__Timecard_Header__r.pse__Total_Hours__c
    render action: 'index'
  end

  private
  def vacation_balance_request_params
    params.require(:vacation_balance_request).permit(:vacation_balance, :start_date, :end_date, :accrual_rate, :salesforce_text)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/vacation_balance_request_helper.rb
module VacationBalanceRequestHelper
  def client
    @client ||= Restforce.new :host => 'test.salesforce.com',
                              :oauth_token => session[:token],
                              :refresh_token => session[:refresh_token],
                              :instance_url => session[:instance_url],
                              :client_id => ENV['SALESFORCE_SANDBOX_KEY'],
                              :client_secret => ENV['SALESFORCE_SANDBOX_SECRET']
  end
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "danger"}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'RnR at ThoughtWorks'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'RnR at ThoughtWorks'}"}
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = favicon_link_tag 'favicon.ico'
    = csrf_meta_tags
  %body

    .container.spacer
      %header.page-header
        %ul.nav.nav-pills.pull-right
          %li
            %p.navbar-text Hello #{@current_user}! (#{link_to 'Log out', logout_path, :class => "navbar-link"})
        %h1 RNR
      .row
        .col-md-4.col-md-offset-4
          = yield
    #footer
      .container
        %hr
        %p © 2014 ThoughtWorks, Inc.

app/views/vacation_balance_request/index.html.haml
= form_for @vacation_balance_request, method: :get, url: calculate_path do |f|
  - if @vacation_balance_request.errors.any?
    .alert.alert-danger
      %h3
        = pluralize(@vacation_balance_request.errors.count, "error")
        occurred:
      %ul
        - @vacation_balance_request.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label :vacation_balance, 'Rollover vacation days as of January 1, 2014', :class => 'control-label'
    = f.text_field :vacation_balance, :class => 'form-control'
  .form-group
    = f.label :start_date, 'Start date',  :class => 'control-label'
    .input-group.date
      = f.text_field :start_date, :class => 'form-control', :placeholder => 'yyyy/mm/dd'
      %span.input-group-addon
        %i{"class" => "glyphicon glyphicon-calendar"}
      -#= f.date_field(:vacation_balance_request, :start_date, value: @vacation_balance_request.start_date,  :class => 'form-control')
  .form-group
    = f.label :end_date, 'End date',  :class => 'control-label'
    .input-group.date
      = f.text_field :end_date, :class => 'form-control', :placeholder => 'yyyy/mm/dd'
      %span.input-group-addon
        %i{"class" => "glyphicon glyphicon-calendar"}
    -#= date_field(:vacation_balance_request, :end_date, value: @vacation_balance_request.end_date,  :class => 'form-control')
  .form-group
    = f.label :accrual_rate, 'Initial accrual rate',  :class => 'control-label'
    = f.text_field :accrual_rate,  :class => 'form-control'
  .form-group
    = f.label :salesforce_text, 'Copy Salesforce text here',  :class => 'control-label'
    = f.text_area :salesforce_text, :class => 'form-control'
  .action
    = f.submit "Calculate vacation days", :class => 'btn btn-primary btn-block'